image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm ci
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
