language: node_js

node_js: 12

install:
  - npm ci

stages:
  - name: test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: release
      script:
        - npm run package
        - cd dist
        - npx semantic-release
