language: node_js

if: tag IS blank

node_js: 12

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

install:
  - |
    npm ci
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

stages:
  - name: test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: test
      script:
        - cd packages/injected-code && npm run build && cd ../../
        - npm run e2e
        - npm test
        - npm run test:samples
        - npm run package
    - stage: release
      script:
        - npm run package
        - npm run build:samples
        - cd dist
        - npx semantic-release
