const SELF_CLOSING_TAGS = new Set([
  '!DOCTYPE',
  '!doctype',
  'input',
  'br',
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
])

export const isSelfClosingTag: (tagName: string) => boolean = tagName =>
  SELF_CLOSING_TAGS.has(tagName)

const ALLOWED_SELF_CLOSING_TAGS = new Set([
  '!DOCTYPE',
  '!doctype',
  'input',
  'br',
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
  // https://developer.mozilla.org/en-US/docs/Web/SVG/Element
  'a',
  'animate',
  'animateMotion',
  'animateTransform',
  'circle',
  'clipPath',
  'color-profile',
  'defs',
  'desc',
  'discard',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotlight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'hatch',
  'hatchpath',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'mesh',
  'meshgradient',
  'meshpath',
  'meshrow',
  'metadata',
  'mpath',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'script',
  'set',
  'solidColor',
  'stop',
  'style',
  'svg',
  'switch',
  'symbol',
  'text',
  'textPath',
  'title',
  'tspan',
  'unknown',
  'use',
  'view',
])

export const isAllowedSelfClosingTag: (tagName: string) => boolean = tagName =>
  ALLOWED_SELF_CLOSING_TAGS.has(tagName)

const HEAD_TAGS = new Set(['meta', 'title', 'link', 'style', 'base', 'script', 'noscript'])
export const isHeadTag = (tagName: string) => HEAD_TAGS.has(tagName)

const ONLY_HEAD_TAGS = new Set(['base']) // TODO title is allowed inside body but only in svg

export const isBodyTag = (tagName: string) => !ONLY_HEAD_TAGS.has(tagName)

const FORM_TAGS = new Set([
  'input',
  'option',
  'optgroup',
  'select',
  'button',
  'datalist',
  'textarea',
])

const OPEN_IMPLIES_CLOSE = {
  tr: new Set(['tr']),
  th: new Set(['th', 'tr']),
  td: new Set(['tr', 'td']),
  thead: new Set(['td', 'tbody']),
  tbody: new Set(['tfoot']),
  li: new Set(['li']),
  p: new Set([
    'p',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'address',
    'article',
    'aside',
    'blockquote',
    'details',
    'div',
    'dl',
    'fieldset',
    'figcaption',
    'figure',
    'footer',
    'form',
    'header',
    'hr',
    'main',
    'nav',
    'ol',
    'pre',
    'section',
    'table',
    'ul',
  ]),
  rt: new Set(['rt', 'rp']),
  rp: new Set(['rt', 'rp']),
  option: new Set(['option', 'optgroup']),
  optgroup: new Set(['optgroup']),
  dd: new Set(['dd', 'dt']),
  dt: new Set(['dd', 'dt']),
}

export const isAutoClosed = (tagName: string, nextTagName: string) =>
  tagName in OPEN_IMPLIES_CLOSE && OPEN_IMPLIES_CLOSE[tagName].has(nextTagName)

export const isAutoClosedAtEnd = (tagName: string) => tagName in OPEN_IMPLIES_CLOSE
