const SELF_CLOSING_TAGS = new Set([
  '!DOCTYPE',
  '!doctype',
  'input',
  'br',
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
])

export const isSelfClosingTag: (tagName: string) => boolean = tagName =>
  SELF_CLOSING_TAGS.has(tagName)

const ALLOWED_SELF_CLOSING_TAGS = new Set([
  '!DOCTYPE',
  '!doctype',
  'input',
  'br',
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
  // https://developer.mozilla.org/en-US/docs/Web/SVG/Element
  'a',
  'animate',
  'animateMotion',
  'animateTransform',
  'circle',
  'clipPath',
  'color-profile',
  'defs',
  'desc',
  'discard',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotlight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'hatch',
  'hatchpath',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'mesh',
  'meshgradient',
  'meshpath',
  'meshrow',
  'metadata',
  'mpath',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'script',
  'set',
  'solidColor',
  'stop',
  'style',
  'svg',
  'switch',
  'symbol',
  'text',
  'textPath',
  'title',
  'tspan',
  'unknown',
  'use',
  'view',
])

export const isAllowedSelfClosingTag: (tagName: string) => boolean = tagName =>
  ALLOWED_SELF_CLOSING_TAGS.has(tagName)

const HEAD_TAGS = new Set(['meta', 'title', 'link', 'style', 'base', 'script', 'noscript'])
export const isHeadTag = (tagName: string) => HEAD_TAGS.has(tagName)

const ONLY_HEAD_TAGS = new Set(['base']) // TODO title is allowed inside body but only in svg

export const isBodyTag = (tagName: string) => !ONLY_HEAD_TAGS.has(tagName)

const AUTO_CLOSED_TAGS = new Set(['rt', 'dd', 'dt', 'li', 'p'])

export const isAutoClosed = (tagName: string) => AUTO_CLOSED_TAGS.has(tagName)
