export { minimizeEdits } from './MinimizeEdits/MinimizeEdits'
export { diff as diff2 } from './Diff/Diff'
export { parse as parse2 } from './Parse/Parse'
export { generateDom } from './GenerateDom/GenerateDom'
export { updateOffsetMap } from './UpdateOffsetMap/UpdateOffsetMap'
export type { SuccessResult, ErrorResult } from './ParseResult/ParseResult'
